name = "abridge.css"
description = "lightweight semantic html CSS Framework."
license = "MIT"
homepage = "https://github.com/Jieiku/abridge.css/"
min_version = "0.17.2"
demo = "https://abridgecss.netlify.app/"

[extra]

[author]
name = "Jake G (jieiku)"
homepage = "https://github.com/jieiku/"
